// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pubsub/v0/service.proto

package pubsub

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Publishes a message to topic
type PublishRequest struct {
	Topic string `protobuf:"bytes,1,opt,name=topic" json:"topic,omitempty"`
	// Can publish one or more message(s) at a time
	Messages [][]byte `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (m *PublishRequest) Reset()                    { *m = PublishRequest{} }
func (m *PublishRequest) String() string            { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()               {}
func (*PublishRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *PublishRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *PublishRequest) GetMessages() [][]byte {
	if m != nil {
		return m.Messages
	}
	return nil
}

// PublishResponse returns any failed messages
type PublishResponse struct {
	FailedMessages []*FailedMessage `protobuf:"bytes,1,rep,name=failed_messages,json=failedMessages" json:"failed_messages,omitempty"`
}

func (m *PublishResponse) Reset()                    { *m = PublishResponse{} }
func (m *PublishResponse) String() string            { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()               {}
func (*PublishResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *PublishResponse) GetFailedMessages() []*FailedMessage {
	if m != nil {
		return m.FailedMessages
	}
	return nil
}

type FailedMessage struct {
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *FailedMessage) Reset()                    { *m = FailedMessage{} }
func (m *FailedMessage) String() string            { return proto.CompactTextString(m) }
func (*FailedMessage) ProtoMessage()               {}
func (*FailedMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *FailedMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *FailedMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// Pull messages off a topic
type PullRequest struct {
	// Must be set on first request and omitted in subsequent requests
	Topic string `protobuf:"bytes,1,opt,name=topic" json:"topic,omitempty"`
	// Optional, timeout in milliseconds
	Timeout int64 `protobuf:"varint,2,opt,name=timeout" json:"timeout,omitempty"`
}

func (m *PullRequest) Reset()                    { *m = PullRequest{} }
func (m *PullRequest) String() string            { return proto.CompactTextString(m) }
func (*PullRequest) ProtoMessage()               {}
func (*PullRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *PullRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *PullRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type PullResponse struct {
	Messages []*ReceivedMessage `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
}

func (m *PullResponse) Reset()                    { *m = PullResponse{} }
func (m *PullResponse) String() string            { return proto.CompactTextString(m) }
func (*PullResponse) ProtoMessage()               {}
func (*PullResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *PullResponse) GetMessages() []*ReceivedMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

type ReceivedMessage struct {
	Ack     []byte `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *ReceivedMessage) Reset()                    { *m = ReceivedMessage{} }
func (m *ReceivedMessage) String() string            { return proto.CompactTextString(m) }
func (*ReceivedMessage) ProtoMessage()               {}
func (*ReceivedMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *ReceivedMessage) GetAck() []byte {
	if m != nil {
		return m.Ack
	}
	return nil
}

func (m *ReceivedMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type AcknowledgeRequest struct {
	Acks [][]byte `protobuf:"bytes,1,rep,name=acks,proto3" json:"acks,omitempty"`
}

func (m *AcknowledgeRequest) Reset()                    { *m = AcknowledgeRequest{} }
func (m *AcknowledgeRequest) String() string            { return proto.CompactTextString(m) }
func (*AcknowledgeRequest) ProtoMessage()               {}
func (*AcknowledgeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *AcknowledgeRequest) GetAcks() [][]byte {
	if m != nil {
		return m.Acks
	}
	return nil
}

type AcknowledgeResponse struct {
	FailedAcks [][]byte `protobuf:"bytes,1,rep,name=failed_acks,json=failedAcks,proto3" json:"failed_acks,omitempty"`
}

func (m *AcknowledgeResponse) Reset()                    { *m = AcknowledgeResponse{} }
func (m *AcknowledgeResponse) String() string            { return proto.CompactTextString(m) }
func (*AcknowledgeResponse) ProtoMessage()               {}
func (*AcknowledgeResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *AcknowledgeResponse) GetFailedAcks() [][]byte {
	if m != nil {
		return m.FailedAcks
	}
	return nil
}

func init() {
	proto.RegisterType((*PublishRequest)(nil), "capsule8.pubsub.v0.PublishRequest")
	proto.RegisterType((*PublishResponse)(nil), "capsule8.pubsub.v0.PublishResponse")
	proto.RegisterType((*FailedMessage)(nil), "capsule8.pubsub.v0.FailedMessage")
	proto.RegisterType((*PullRequest)(nil), "capsule8.pubsub.v0.PullRequest")
	proto.RegisterType((*PullResponse)(nil), "capsule8.pubsub.v0.PullResponse")
	proto.RegisterType((*ReceivedMessage)(nil), "capsule8.pubsub.v0.ReceivedMessage")
	proto.RegisterType((*AcknowledgeRequest)(nil), "capsule8.pubsub.v0.AcknowledgeRequest")
	proto.RegisterType((*AcknowledgeResponse)(nil), "capsule8.pubsub.v0.AcknowledgeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PubsubService service

type PubsubServiceClient interface {
	// Publishes messages to a topic
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	// Pulls messages off of a topic
	Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (PubsubService_PullClient, error)
	Acknowledge(ctx context.Context, in *AcknowledgeRequest, opts ...grpc.CallOption) (*AcknowledgeResponse, error)
}

type pubsubServiceClient struct {
	cc *grpc.ClientConn
}

func NewPubsubServiceClient(cc *grpc.ClientConn) PubsubServiceClient {
	return &pubsubServiceClient{cc}
}

func (c *pubsubServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := grpc.Invoke(ctx, "/capsule8.pubsub.v0.PubsubService/Publish", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubsubServiceClient) Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (PubsubService_PullClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PubsubService_serviceDesc.Streams[0], c.cc, "/capsule8.pubsub.v0.PubsubService/Pull", opts...)
	if err != nil {
		return nil, err
	}
	x := &pubsubServicePullClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PubsubService_PullClient interface {
	Recv() (*PullResponse, error)
	grpc.ClientStream
}

type pubsubServicePullClient struct {
	grpc.ClientStream
}

func (x *pubsubServicePullClient) Recv() (*PullResponse, error) {
	m := new(PullResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pubsubServiceClient) Acknowledge(ctx context.Context, in *AcknowledgeRequest, opts ...grpc.CallOption) (*AcknowledgeResponse, error) {
	out := new(AcknowledgeResponse)
	err := grpc.Invoke(ctx, "/capsule8.pubsub.v0.PubsubService/Acknowledge", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PubsubService service

type PubsubServiceServer interface {
	// Publishes messages to a topic
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	// Pulls messages off of a topic
	Pull(*PullRequest, PubsubService_PullServer) error
	Acknowledge(context.Context, *AcknowledgeRequest) (*AcknowledgeResponse, error)
}

func RegisterPubsubServiceServer(s *grpc.Server, srv PubsubServiceServer) {
	s.RegisterService(&_PubsubService_serviceDesc, srv)
}

func _PubsubService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubsubServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/capsule8.pubsub.v0.PubsubService/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubsubServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubsubService_Pull_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PubsubServiceServer).Pull(m, &pubsubServicePullServer{stream})
}

type PubsubService_PullServer interface {
	Send(*PullResponse) error
	grpc.ServerStream
}

type pubsubServicePullServer struct {
	grpc.ServerStream
}

func (x *pubsubServicePullServer) Send(m *PullResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PubsubService_Acknowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubsubServiceServer).Acknowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/capsule8.pubsub.v0.PubsubService/Acknowledge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubsubServiceServer).Acknowledge(ctx, req.(*AcknowledgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PubsubService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "capsule8.pubsub.v0.PubsubService",
	HandlerType: (*PubsubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _PubsubService_Publish_Handler,
		},
		{
			MethodName: "Acknowledge",
			Handler:    _PubsubService_Acknowledge_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Pull",
			Handler:       _PubsubService_Pull_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pubsub/v0/service.proto",
}

func init() { proto.RegisterFile("pubsub/v0/service.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 493 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x51, 0x6b, 0xd4, 0x40,
	0x10, 0xc7, 0x49, 0xae, 0x7a, 0x3a, 0x97, 0xb6, 0xba, 0x15, 0x8d, 0xa1, 0xd0, 0x73, 0x0b, 0x7a,
	0x14, 0x49, 0x8e, 0x0a, 0x52, 0x0a, 0xa5, 0xb4, 0x0f, 0x3e, 0x08, 0xe2, 0x11, 0xdf, 0x04, 0x91,
	0xcd, 0xde, 0x5c, 0xba, 0x24, 0x97, 0x8d, 0xd9, 0x24, 0x22, 0xe2, 0x8b, 0x5f, 0xc1, 0x8f, 0xe6,
	0xb3, 0x6f, 0x7e, 0x10, 0xc9, 0x6e, 0xee, 0x9a, 0xf3, 0xce, 0xfa, 0x74, 0x3b, 0x97, 0xff, 0xcc,
	0xfc, 0x7f, 0x33, 0xbb, 0xf0, 0x28, 0xaf, 0x22, 0x55, 0x45, 0x41, 0x3d, 0x0e, 0x14, 0x16, 0xb5,
	0xe0, 0xe8, 0xe7, 0x85, 0x2c, 0x25, 0x21, 0x9c, 0xe5, 0xaa, 0x4a, 0xf1, 0xc4, 0x37, 0x0a, 0xbf,
	0x1e, 0x7b, 0xfb, 0xb1, 0x94, 0x71, 0x8a, 0x01, 0xcb, 0x45, 0xc0, 0xb2, 0x4c, 0x96, 0xac, 0x14,
	0x32, 0x53, 0x26, 0x83, 0x5e, 0xc2, 0xce, 0xa4, 0x8a, 0x52, 0xa1, 0xae, 0x42, 0xfc, 0x54, 0xa1,
	0x2a, 0xc9, 0x03, 0xb8, 0x55, 0xca, 0x5c, 0x70, 0xd7, 0x1a, 0x5a, 0xa3, 0xbb, 0xa1, 0x09, 0x88,
	0x07, 0x77, 0xe6, 0xa8, 0x14, 0x8b, 0x51, 0xb9, 0xf6, 0xb0, 0x37, 0x72, 0xc2, 0x65, 0x4c, 0x3f,
	0xc0, 0xee, 0xb2, 0x86, 0xca, 0x65, 0xa6, 0x90, 0xbc, 0x86, 0xdd, 0x19, 0x13, 0x29, 0x4e, 0x3f,
	0x2e, 0xb3, 0xac, 0x61, 0x6f, 0x34, 0x38, 0x7e, 0xe2, 0xaf, 0x5b, 0xf4, 0x5f, 0x69, 0xe9, 0x1b,
	0xa3, 0x0c, 0x77, 0x66, 0xdd, 0x50, 0xd1, 0x73, 0xd8, 0x5e, 0x11, 0x10, 0x17, 0xfa, 0x39, 0xfb,
	0x92, 0x4a, 0x36, 0xd5, 0x1e, 0x9d, 0x70, 0x11, 0x36, 0xde, 0xb1, 0x28, 0x64, 0xe1, 0xda, 0xc6,
	0xbb, 0x0e, 0xe8, 0x19, 0x0c, 0x26, 0x55, 0x9a, 0xde, 0x0c, 0xe8, 0x42, 0xbf, 0x14, 0x73, 0x94,
	0x55, 0xa9, 0x93, 0x7b, 0xe1, 0x22, 0xa4, 0x6f, 0xc1, 0x31, 0xe9, 0x2d, 0xdb, 0x79, 0x67, 0x14,
	0x06, 0xea, 0x70, 0x13, 0x54, 0x88, 0x1c, 0x45, 0x7d, 0x8d, 0x75, 0x3d, 0xaf, 0x33, 0xd8, 0xfd,
	0xeb, 0x23, 0xb9, 0x07, 0x3d, 0xc6, 0x93, 0x16, 0xa7, 0x39, 0x76, 0x21, 0xed, 0x15, 0x48, 0x3a,
	0x02, 0x72, 0xc1, 0x93, 0x4c, 0x7e, 0x4e, 0x71, 0x1a, 0xe3, 0x82, 0x8a, 0xc0, 0x16, 0xe3, 0x89,
	0x71, 0xe4, 0x84, 0xfa, 0x4c, 0x5f, 0xc2, 0xde, 0x8a, 0xb2, 0x05, 0x38, 0x80, 0x41, 0xbb, 0x9c,
	0x4e, 0x06, 0x98, 0xbf, 0x2e, 0x78, 0xa2, 0x8e, 0x7f, 0xd9, 0xb0, 0x3d, 0xd1, 0x20, 0xef, 0xcc,
	0xf5, 0x22, 0x39, 0xf4, 0xdb, 0x15, 0x13, 0xba, 0x09, 0x76, 0xf5, 0x0e, 0x79, 0x87, 0x37, 0x6a,
	0x8c, 0x0d, 0xba, 0xff, 0xfd, 0xe7, 0xef, 0x1f, 0xf6, 0x43, 0x7a, 0xbf, 0xb9, 0xc7, 0x7a, 0x09,
	0xc1, 0x57, 0xfd, 0xf3, 0xed, 0xd4, 0x3a, 0x22, 0x33, 0xd8, 0x6a, 0xa6, 0x4e, 0x0e, 0x36, 0x97,
	0x5a, 0xae, 0xd3, 0x1b, 0xfe, 0x5b, 0xd0, 0x36, 0x7a, 0xac, 0x1b, 0xed, 0x91, 0xf5, 0x46, 0x63,
	0x8b, 0x14, 0x30, 0xe8, 0xcc, 0x88, 0x3c, 0xdd, 0x54, 0x6d, 0x7d, 0xdc, 0xde, 0xb3, 0xff, 0xea,
	0xda, 0xe6, 0x44, 0x37, 0x77, 0x68, 0xbf, 0x69, 0xce, 0x78, 0x72, 0x6a, 0x1d, 0x5d, 0xfa, 0xef,
	0x9f, 0xc7, 0xa2, 0xbc, 0xaa, 0x22, 0x9f, 0xcb, 0x79, 0xb0, 0x28, 0x14, 0x14, 0xc8, 0x78, 0x29,
	0x6a, 0x3c, 0x09, 0xf2, 0x24, 0xd6, 0xef, 0xd5, 0x94, 0x8e, 0x6e, 0xeb, 0xb7, 0xfa, 0xe2, 0x4f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x25, 0x38, 0xd0, 0x31, 0xf8, 0x03, 0x00, 0x00,
}
