// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package telemetry is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	GetEventsRequest
	GetEventsResponse
*/
package telemetry

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import capsule8_api_v01 "github.com/capsule8/api/v0"
import capsule8_api_v0 "github.com/capsule8/api/v0"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetEventsRequest struct {
	Sub *capsule8_api_v01.Subscription `protobuf:"bytes,1,opt,name=sub" json:"sub,omitempty"`
}

func (m *GetEventsRequest) Reset()                    { *m = GetEventsRequest{} }
func (m *GetEventsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetEventsRequest) ProtoMessage()               {}
func (*GetEventsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetEventsRequest) GetSub() *capsule8_api_v01.Subscription {
	if m != nil {
		return m.Sub
	}
	return nil
}

type GetEventsResponse struct {
	Events []*capsule8_api_v0.Event `protobuf:"bytes,1,rep,name=events" json:"events,omitempty"`
}

func (m *GetEventsResponse) Reset()                    { *m = GetEventsResponse{} }
func (m *GetEventsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetEventsResponse) ProtoMessage()               {}
func (*GetEventsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetEventsResponse) GetEvents() []*capsule8_api_v0.Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*GetEventsRequest)(nil), "telemetry.GetEventsRequest")
	proto.RegisterType((*GetEventsResponse)(nil), "telemetry.GetEventsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TelemetryService service

type TelemetryServiceClient interface {
	// Publishes messages to a topic
	GetEvents(ctx context.Context, in *capsule8_api_v01.Subscription, opts ...grpc.CallOption) (TelemetryService_GetEventsClient, error)
}

type telemetryServiceClient struct {
	cc *grpc.ClientConn
}

func NewTelemetryServiceClient(cc *grpc.ClientConn) TelemetryServiceClient {
	return &telemetryServiceClient{cc}
}

func (c *telemetryServiceClient) GetEvents(ctx context.Context, in *capsule8_api_v01.Subscription, opts ...grpc.CallOption) (TelemetryService_GetEventsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_TelemetryService_serviceDesc.Streams[0], c.cc, "/telemetry.TelemetryService/GetEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &telemetryServiceGetEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TelemetryService_GetEventsClient interface {
	Recv() (*GetEventsResponse, error)
	grpc.ClientStream
}

type telemetryServiceGetEventsClient struct {
	grpc.ClientStream
}

func (x *telemetryServiceGetEventsClient) Recv() (*GetEventsResponse, error) {
	m := new(GetEventsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for TelemetryService service

type TelemetryServiceServer interface {
	// Publishes messages to a topic
	GetEvents(*capsule8_api_v01.Subscription, TelemetryService_GetEventsServer) error
}

func RegisterTelemetryServiceServer(s *grpc.Server, srv TelemetryServiceServer) {
	s.RegisterService(&_TelemetryService_serviceDesc, srv)
}

func _TelemetryService_GetEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(capsule8_api_v01.Subscription)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TelemetryServiceServer).GetEvents(m, &telemetryServiceGetEventsServer{stream})
}

type TelemetryService_GetEventsServer interface {
	Send(*GetEventsResponse) error
	grpc.ServerStream
}

type telemetryServiceGetEventsServer struct {
	grpc.ServerStream
}

func (x *telemetryServiceGetEventsServer) Send(m *GetEventsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _TelemetryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.TelemetryService",
	HandlerType: (*TelemetryServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEvents",
			Handler:       _TelemetryService_GetEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xbf, 0x4b, 0xc4, 0x30,
	0x14, 0xc7, 0x0d, 0x07, 0x07, 0x97, 0x43, 0x38, 0x33, 0xc8, 0x51, 0x15, 0x8e, 0x4c, 0x9d, 0x5e,
	0x4a, 0x5d, 0xdc, 0x8b, 0xb8, 0x38, 0xb5, 0xfe, 0x01, 0xb6, 0xe5, 0x0d, 0x81, 0xda, 0xc4, 0xbc,
	0x24, 0xe0, 0x7f, 0x2f, 0x6d, 0x6d, 0x29, 0x16, 0x6e, 0x4d, 0x3e, 0xdf, 0x5f, 0x8f, 0xdf, 0x12,
	0xba, 0xa8, 0x5b, 0x04, 0xeb, 0x8c, 0x37, 0xe2, 0xe0, 0xb1, 0xc3, 0x2f, 0xf4, 0xee, 0x27, 0x91,
	0x6d, 0x6d, 0x29, 0x74, 0xf8, 0xa2, 0x6a, 0xab, 0x55, 0xcc, 0x14, 0x85, 0x86, 0x5a, 0xa7, 0xad,
	0xd7, 0xa6, 0x9f, 0xf0, 0xe4, 0xe1, 0x3f, 0x83, 0x11, 0x7b, 0x3f, 0x7d, 0xca, 0x82, 0x9f, 0xde,
	0xd0, 0xbf, 0x0e, 0x2f, 0x54, 0xe2, 0x77, 0x40, 0xf2, 0x42, 0xf1, 0x1d, 0x85, 0xe6, 0xcc, 0x2e,
	0x2c, 0x3d, 0xe6, 0x4f, 0x30, 0xcb, 0xa1, 0xb6, 0x1a, 0x62, 0x06, 0xd5, 0x2a, 0xa2, 0x1c, 0x48,
	0x59, 0xf0, 0xbb, 0x95, 0x09, 0x59, 0xd3, 0x13, 0x0a, 0xe0, 0xfb, 0x31, 0x88, 0xce, 0xec, 0xb2,
	0x4b, 0x8f, 0xf9, 0xfd, 0xc6, 0x68, 0x14, 0x94, 0x7f, 0x54, 0xfe, 0xc9, 0x4f, 0x1f, 0xf3, 0xae,
	0x6a, 0xda, 0x2b, 0xde, 0xf9, 0x61, 0x31, 0x16, 0xd7, 0x9b, 0x24, 0x8f, 0xb0, 0x9c, 0x05, 0x36,
	0x6d, 0xe4, 0x4d, 0xc6, 0x9a, 0xfd, 0x38, 0xf9, 0xf9, 0x37, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x4b,
	0x86, 0xb6, 0x4f, 0x01, 0x00, 0x00,
}
