#!/bin/sh

function apply_license_to_go() {
	local filename=$1
	local tmpfile=$(mktemp)

	cat <<EOF > ${tmpfile}
// Copyright 2017 Capsule8, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

EOF
	
	cat ${filename} >> ${tmpfile}
	mv ${tmpfile} ${filename}
}

function main() {
	local filename=$1
	
	if [[ -z "${filename}" ]]; then
		echo "usage: $0 FILENAME"
		exit 1
	fi
	
	if [[ ! -f ${filename} ]]; then
		echo "Could not open ${filename}"
		exit 1
	fi

	case ${filename} in
	*.c)
		if [[ ! $(head -1 ${filename} | grep Copyright 2>/dev/null) ]]; then
			echo "Applying copyright and license to ${filename}"
			
			apply_license_to_go ${filename}
		fi
		;;
	
	*.go)
		if [[ ! $(head -1 ${filename} | grep Copyright 2>/dev/null) ]]; then
			echo "Applying copyright and license to ${filename}"
			
			apply_license_to_go ${filename}
		fi
		;;
	
	*.proto)
		if [[ ! $(head -1 ${filename} | grep Copyright 2>/dev/null) ]]; then
			echo "Applying copyright and license to ${filename}"
			
			apply_license_to_go ${filename}
		fi
		;;

	esac
}

main $@
